<?php
/**
 * @author Jörn Friedrich Dreyer <jfd@butonic.de>
 *
 * @copyright Copyright (c) 2016, ownCloud GmbH.
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

namespace OCA\ConfigReport\Controller;

use OC\Http\Client\Response;
use OCA\Activity\Data;
use OCA\ConfigReport\Http\ReportResponse;
use OCA\ConfigReport\ReportDataCollector;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\DataResponse;
use OCP\IConfig;
use OCP\IRequest;

/**
 * Class ReportController is used to handle report generation on the admin
 * settings page
 *
 * @package OCA\ConfigReport\Controller
 */
class ReportController extends Controller {

	/**
	 * @var IConfig
	 */
	private $config;

	/**
	 * @var ReportDataCollector
	 */
	private $reportDataCollector;

	/**
	 * @param string $AppName
	 * @param IRequest $request
	 * @param IConfig $config
	 * @param ReportDataCollector $reportDataCollector
	 */
	public function __construct(
		$AppName,
		IRequest $request,
		IConfig $config,
		ReportDataCollector $reportDataCollector
	) {
		$this->config = $config;
		$this->reportDataCollector = $reportDataCollector;
		parent::__construct($AppName, $request);
	}

	/**
	 * AJAX handler for getting the config report
	 *
	 * @NoCSRFRequired
	 * @return ReportResponse with the report
	 */
	public function getReport() {
		return new ReportResponse('', '', $this->reportDataCollector->getReportJson());
	}

	/**
	 * API-Handler which is used to get web config-report from cli. Auth-Token
	 * is generated by the cli-app for onetime use.
	 *
	 * @NoCSRFRequired
	 * @NoAdminRequired
	 * @PublicPage
	 *
	 * @return ReportResponse|DataResponse with the report
	 */
	public function fromCli() {
		$cfg = $this->config;
		$actualToken = $cfg->getAppValue('configreport', 'token');

		// token generated by cli app
		$passedToken = $this->request->getParam('token');

		if (($actualToken !== $passedToken) || (empty($passedToken) || empty($actualToken))) {
			return new DataResponse([], Http::STATUS_FORBIDDEN, []);
		}

		$resp = new ReportResponse('', '', $this->reportDataCollector->getReportJson());
		$cfg->deleteAppValue('configreport', 'token');

		return $resp;
	}
}
