workspace:
  base: /var/www/owncloud
  path: apps/configreport

branches: [master, release*]

pipeline:
  install-server:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}
    exclude: apps/configreport

  code-compliance-check:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      # currently fails since we rely on OC_Util
      # - make test-php-codecheck
      - make test-php-lint

  unit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - make test-php-unit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
     - tests/output
    files:
     - "*.xml"
    when:
      event: [push, pull_request]
      status:  [ success, failure ]
      matrix:
        COVERAGE: true

matrix:
  include:

    #master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa

    # stable10
    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa

