workspace:
  base: /var/www/owncloud
  path: apps/configreport

branches: [master, release*]

pipeline:
  install-core:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}
    exclude: apps/configreport
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME}
    db_host: ${DB_HOST}
    db_username: autotest
    db_password: owncloud
    when:
      matrix:
        NEED_CORE: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e configreport
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 0
    when:
      matrix:
        NEED_INSTALL_APP: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - chmod +x /var/www/owncloud/tests/acceptance/run.sh
    when:
      matrix:
        NEED_SERVER: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log
    when:
      matrix:
        NEED_SERVER: true

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://owncloud
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - make test-acceptance-api
    when:
      matrix:
        TEST_SUITE: api-acceptance

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
      - tests/output/*.xml
    when:
      event: [push, pull_request]
      status:  [ success, failure ]
      matrix:
        COVERAGE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [slack_webhook]
    channel: builds
    when:
      status: [failure, changed]
      event: [push, tag]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_HOST: mysql

  mysqlmb4:
    image: mysql:5.7
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_HOST: mysqlmb4

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME}
    when:
      matrix:
        DB_HOST: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
       - ORACLE_USER=system
       - ORACLE_PASSWORD=oracle
       - ORACLE_DB=${DB_NAME}
    when:
      matrix:
        DB_HOST: oci

  owncloud:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        NEED_SERVER: true

matrix:
  include:
    # owncloud-coding-standard
    - PHP_VERSION: 5.6
      TEST_SUITE: owncloud-coding-standard

    - PHP_VERSION: 7.2
      TEST_SUITE: owncloud-coding-standard

    # unit tests
    # master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: oci
      DB_TYPE: oci
      DB_NAME: XE

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: pgsql
      DB_TYPE: pgsql
      DB_NAME: owncloud

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: mysql
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: mysqlmb4
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      NEED_CORE: true

    # stable10
    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: oci
      DB_TYPE: oci
      DB_NAME: XE

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: pgsql
      DB_TYPE: pgsql
      DB_NAME: owncloud

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: mysql
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      DB_HOST: mysqlmb4
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      NEED_CORE: true

    # acceptance tests
    # master
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiConfigReport
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      DB_HOST: oci
      DB_TYPE: oci
      DB_NAME: XE

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiConfigReport
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      DB_HOST: pgsql
      DB_TYPE: pgsql
      DB_NAME: owncloud

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiConfigReport
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      DB_HOST: mysql
      DB_TYPE: mysql
      DB_NAME: owncloud

    # stable10
    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiConfigReport
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      DB_HOST: oci
      DB_TYPE: oci
      DB_NAME: XE

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiConfigReport
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      DB_HOST: mysql
      DB_TYPE: mysql
      DB_NAME: owncloud
