language: php
php:
- 5.6 
- 7

env:
 global:
 -CORE_BRANCH=master
 -APP_NAME=configreport
 matrix:
 -DB=SQLLITE
 
branches:
 only:
  -master
  -/^stable\d+(\.\d+)?$/
 
before install:
 -wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
 -bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

 #Add some output debugging information
 -cd ../core
 -./occ check
 -./occ status
 -./occ app:list
 -./occ app:ENABLE $APP_NAME
 -./occ app:list
 
matrix:
 include:
  -php: 5.6
   env: DB=mysql
  -php:5.6
   env: DB=pgsql
 fast_finish: true  
